/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comptabilitat.botiga;

import static comptabilitat.botiga.Dades.ticketsPendents;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.ListModel;

import jxl.read.biff.BiffException;

/**
 *
 * @author Broquil
 */
public class Interfase extends javax.swing.JFrame {

    /**
     * Carrega els productes per defecte a les llistes de noms i granel
     */
    private void carregarNoms() {

        DefaultListModel a = new DefaultListModel(); 
        DefaultListModel b = new DefaultListModel();
        
        for(int i=0; i<14; i++){
            a.addElement(Dades.llistaProductes.get(i).nom);
        }
        llistaNoms.setModel(a);
        
        Dades.verdura.entrySet().stream().forEach((p) -> {
            b.addElement(p.getKey());
        });
        llistaGranel.setModel(b);
    }
    
    /**
     * Refresca les llistes de productes i preus
     */
    private void refrescaLlistes() {
        Dades.ticketActual.calcularTotals();
        DefaultListModel Noms = new DefaultListModel();
        DefaultListModel Preus = new DefaultListModel();
        DefaultListModel Quantitats = new DefaultListModel();
        DefaultListModel Totals = new DefaultListModel();
        DecimalFormat df = new DecimalFormat("#,##0.00");
        float preuTotal = 0;
        for(ItemTicket t: Dades.ticketActual.llistaItems){
                Noms.addElement(t.nom);
                Preus.addElement(df.format(t.preu));
                Quantitats.addElement(t.quantitat);
                Totals.addElement(df.format(t.total));
                preuTotal+=t.total;
        }
        nomProductes.setModel(Noms);
        preus.setModel(Preus);
        quantitats.setModel(Quantitats);
        totals.setModel(Totals);
        total.setText(String.valueOf(df.format(preuTotal)));
    }
    
    /**
     * Elimina el contingut de totes les llistes i posa el total a 0
     */
    private void buidaLlistes() {
        nomProductes.removeAll();
        preus.removeAll();
        quantitats.removeAll();
        totals.removeAll();
        total.setText("0");
        refrescaLlistes();
    }

    /**
     * Mou el marc visible de les llistes per mostrar l'index seleccionat
     */
    private void mostrarIndex() {
        nomProductes.ensureIndexIsVisible(nomProductes.getSelectedIndex());
        quantitats.ensureIndexIsVisible(quantitats.getSelectedIndex());
        preus.ensureIndexIsVisible(preus.getSelectedIndex());
        totals.ensureIndexIsVisible(totals.getSelectedIndex());
    }
 
    /**
     * Creates new form Interfase2
     */
    public Interfase() {
        initComponents();
        carregarNoms();
        Funcions.definirImpresora();
        this.setName("Comtabilitat SuperEva");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        totals = new javax.swing.JList();
        total = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        nomProductes = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        llistaNoms = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        quantitats = new javax.swing.JList();
        entrada = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        preus = new javax.swing.JList();
        cercaNom = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        llistaGranel = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        gestioDades = new javax.swing.JMenu();
        carregarExcel = new javax.swing.JMenuItem();
        guardarDades = new javax.swing.JMenuItem();
        carregaDades = new javax.swing.JMenuItem();
        veureClients = new javax.swing.JMenuItem();
        mostraLlistes = new javax.swing.JMenu();
        veurePrestatges = new javax.swing.JMenuItem();
        veureTicketsPendents = new javax.swing.JMenuItem();
        veureVendes = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        recuperarTicket = new javax.swing.JMenuItem();
        aparcarTicket = new javax.swing.JMenuItem();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1024, 800));
        setResizable(false);

        totals.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totals.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        totals.setToolTipText("");
        totals.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                totalsValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(totals);

        total.setEditable(false);
        total.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        total.setToolTipText("Total");

        nomProductes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nomProductes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        nomProductes.setToolTipText("");
        nomProductes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                nomProductesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(nomProductes);

        llistaNoms.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        llistaNoms.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llistaNomsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                none(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                llistaNomsMouseExited(evt);
            }
        });
        jScrollPane6.setViewportView(llistaNoms);

        quantitats.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        quantitats.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        quantitats.setToolTipText("");
        quantitats.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                quantitatsValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(quantitats);

        entrada.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        entrada.setHighlighter(null);
        entrada.setNextFocusableComponent(cercaNom);
        entrada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                entradaFocusGained(evt);
            }
        });
        entrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                entradaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                entradaKeyReleased(evt);
            }
        });

        preus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        preus.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        preus.setToolTipText("");
        preus.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                preusValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(preus);

        cercaNom.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cercaNom.setHighlighter(null);
        cercaNom.setNextFocusableComponent(entrada);
        cercaNom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cercaNomFocusGained(evt);
            }
        });
        cercaNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cercaNomActionPerformed(evt);
            }
        });
        cercaNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cercaNomKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cercaNomKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cercaNomKeyTyped(evt);
            }
        });

        jLabel1.setText("Nom productes");

        jLabel2.setText("Quantitat");

        jLabel3.setText("Preu");

        jLabel5.setText("Total");

        llistaGranel.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        llistaGranel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llistaGranelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                llistaGranelnone(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                llistaGranelMouseExited(evt);
            }
        });
        jScrollPane7.setViewportView(llistaGranel);

        jLabel6.setText("Produces per nom:");

        jLabel7.setText("Productes a pes:");

        gestioDades.setText("Gestió Dades");

        carregarExcel.setText("Carregar Excel");
        carregarExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carregarExcelActionPerformed(evt);
            }
        });
        gestioDades.add(carregarExcel);

        guardarDades.setText("Guardar dades");
        guardarDades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarDadesActionPerformed(evt);
            }
        });
        gestioDades.add(guardarDades);

        carregaDades.setText("Carregar dades");
        carregaDades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carregaDadesActionPerformed(evt);
            }
        });
        gestioDades.add(carregaDades);

        veureClients.setText("Llista de clients");
        veureClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veureClientsActionPerformed(evt);
            }
        });
        gestioDades.add(veureClients);

        jMenuBar1.add(gestioDades);

        mostraLlistes.setText("Veure");

        veurePrestatges.setText("Estat prestatges");
        veurePrestatges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veurePrestatgesActionPerformed(evt);
            }
        });
        mostraLlistes.add(veurePrestatges);

        veureTicketsPendents.setText("Tickets pendents");
        veureTicketsPendents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veureTicketsPendentsActionPerformed(evt);
            }
        });
        mostraLlistes.add(veureTicketsPendents);

        veureVendes.setText("Vendes");
        veureVendes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veureVendesActionPerformed(evt);
            }
        });
        mostraLlistes.add(veureVendes);

        jMenuBar1.add(mostraLlistes);

        jMenu1.setText("Tickets");

        recuperarTicket.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        recuperarTicket.setText("Recuperar ticket");
        recuperarTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recuperarTicketActionPerformed(evt);
            }
        });
        jMenu1.add(recuperarTicket);

        aparcarTicket.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        aparcarTicket.setText("Aparcar ticket");
        aparcarTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aparcarTicketActionPerformed(evt);
            }
        });
        jMenu1.add(aparcarTicket);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel6))
                                        .addGap(148, 148, 148))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGap(12, 12, 12)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(0, 180, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addComponent(entrada)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cercaNom, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane3)
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(237, 237, 237))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(cercaNom, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void carregarExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carregarExcelActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int returnVal = fileChooser.showOpenDialog(fileChooser);
        String f;
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            f = fileChooser.getName();
            try {
                Funcions.carregarExcel(f);
            } catch (IOException | BiffException ex) {
                Logger.getLogger(Interfase.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_carregarExcelActionPerformed

    private void guardarDadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarDadesActionPerformed
        try {
            FileOutputStream fout = new FileOutputStream("prova.txt");
            ObjectOutputStream oos = new ObjectOutputStream(fout);
            oos.writeObject(Dades.llistaProductes);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Interfase.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Interfase.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_guardarDadesActionPerformed

    private void veureClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veureClientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veureClientsActionPerformed

    private void veurePrestatgesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veurePrestatgesActionPerformed

        JFrame frame = new JFrame("Productes als prestatges");
        frame.setLocationRelativeTo(null);
        Llistats prestatges = new Llistats();
        prestatges.carregarLlistesPrestatge();
        frame.setSize(810, 700);
        frame.add(prestatges);
        frame.setLocationRelativeTo(this);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frame.setVisible(true);
  
    }//GEN-LAST:event_veurePrestatgesActionPerformed

    private void veureTicketsPendentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veureTicketsPendentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_veureTicketsPendentsActionPerformed

    private void carregaDadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carregaDadesActionPerformed
        try {
            // TODO add your handling code here:
            Funcions.obreDades();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(Interfase.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_carregaDadesActionPerformed

    private void none(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_none

    }//GEN-LAST:event_none

    
    //-----------Finestra cerca per nom---------------------
    
    private void cercaNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cercaNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cercaNomActionPerformed

    private void cercaNomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cercaNomKeyPressed
        // TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ENTER:
                if(!llistaNoms.isSelectionEmpty()){
                    ListModel l = llistaNoms.getModel();
                    int i = llistaNoms.getSelectedIndex();
                    Object e = l.getElementAt(i);
                    String nom = e.toString();
                    Producte p = Funcions.cercaPerNom(nom);
                    ItemTicket t = new ItemTicket();
                    t.nom = p.nom;
                    t.preu = p.preu;
                    if(!entrada.getText().isEmpty()){
                        t.quantitat = Float.parseFloat(entrada.getText());
                    }else{
                        t.quantitat = 1;
                    }
                    Dades.ticketActual.afegirProducte(t);
                    refrescaLlistes();
                    nomProductes.setSelectedIndex(i);
                }else{
                    ListModel l = llistaGranel.getModel();
                    int i = llistaGranel.getSelectedIndex();
                    String nom = l.getElementAt(i).toString();
                    Map.Entry<String, Float> a = Funcions.cercaPerNomGranel(nom);
                    ItemTicket t = new ItemTicket();
                    t.nom = a.getKey();
                    t.preu = a.getValue();
                    if(!entrada.getText().isEmpty()){
                        t.quantitat = Float.parseFloat(entrada.getText());
                    }else{
                        t.quantitat = 1;
                    }
                    Dades.ticketActual.afegirProducte(t);
                    refrescaLlistes();
                    entrada.setText("");
                    llistaGranel.setSelectedIndex(i);
                }
               
            break;                
        }
        mostrarIndex();
    }//GEN-LAST:event_cercaNomKeyPressed

    private void llistaNomsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llistaNomsMouseClicked
        // TODO add your handling code here:
        ListModel l = llistaNoms.getModel();
        int i = llistaNoms.getSelectedIndex();
        Object e = l.getElementAt(i);
        String nom = e.toString();
        Producte p = Funcions.cercaPerNom(nom);
        ItemTicket t = new ItemTicket();
        t.nom = p.nom;
        t.preu = p.preu;
        if(!entrada.getText().isEmpty()){
            t.quantitat = Float.parseFloat(entrada.getText());
        }else{
            t.quantitat = 1;
        }
        Dades.ticketActual.afegirProducte(t);
        refrescaLlistes();
        nomProductes.setSelectedIndex(nomProductes.getModel().getSize() - 1);
        mostrarIndex();
    }//GEN-LAST:event_llistaNomsMouseClicked

    private void cercaNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cercaNomKeyTyped
        
    }//GEN-LAST:event_cercaNomKeyTyped
     
    private void cercaNomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cercaNomKeyReleased
        
        switch(evt.getKeyCode()){

            case KeyEvent.VK_DOWN:
                if(llistaNoms.getSelectedIndex()>=0){
                    int q = llistaNoms.getSelectedIndex()+1;
                    if(q<llistaNoms.getModel().getSize()){
                        llistaNoms.setSelectedIndex(q);
                    }else{
                        llistaNoms.setSelectedIndex(0);
                    }
                }else{
                    int q = llistaGranel.getSelectedIndex()+1;
                    if(q<llistaGranel.getModel().getSize()){
                        llistaGranel.setSelectedIndex(q);
                    }else{
                        llistaGranel.setSelectedIndex(0);
                    }
                }
                
            break;
                
            case KeyEvent.VK_UP:
                if(llistaNoms.getSelectedIndex()>=0){
                    int f = llistaNoms.getSelectedIndex()-1;
                    if(f>=0){
                        llistaNoms.setSelectedIndex(f);
                    }
                }else{
                    int f = llistaGranel.getSelectedIndex()-1;
                    if(f>=0){
                        llistaGranel.setSelectedIndex(f);
                    }
                }
                
            break;
                
            case KeyEvent.VK_RIGHT: 
                
                if(llistaNoms.getSelectedIndex() > llistaGranel.getModel().getSize()){
                    
                    llistaGranel.setSelectedIndex(llistaGranel.getModel().getSize()-1);
                    
                }else{
                    
                    llistaGranel.setSelectedIndex(llistaNoms.getSelectedIndex());
                                        
                }
                llistaNoms.clearSelection();
            break;
                
            case KeyEvent.VK_LEFT:
                if(llistaGranel.getSelectedIndex() > llistaNoms.getModel().getSize()){
                    
                    llistaNoms.setSelectedIndex(llistaNoms.getModel().getSize()-1);
                    
                }else{
                    
                    llistaNoms.setSelectedIndex(llistaGranel.getSelectedIndex());
                                        
                }
                llistaGranel.clearSelection();
            break;

            default:
                int g = llistaGranel.getSelectedIndex();
                int n = llistaNoms.getSelectedIndex();
                
                String c = cercaNom.getText().toUpperCase();
                DefaultListModel llistaElements = Funcions.cercaPorcioProducte(c);
                DefaultListModel llistaVerdura = Funcions.cercaPorcioGranel(c);

                DefaultListModel a = new DefaultListModel();
                DefaultListModel b = new DefaultListModel();

                int i = 0;
                while(!llistaElements.isEmpty() && i<14){
                    a.addElement(llistaElements.firstElement());
                    llistaElements.remove(0);
                    i++;
                }

                i = 0;
                while(!llistaVerdura.isEmpty() && i<14){
                    b.addElement(llistaVerdura.firstElement());
                    llistaVerdura.remove(0);
                    i++;
                }

                llistaNoms.setModel(a);
                llistaGranel.setModel(b);
                
                llistaGranel.setSelectedIndex(g);
                llistaNoms.setSelectedIndex(n);
                
                nomProductes.setSelectedIndex(nomProductes.getModel().getSize() - 1);
                
                mostrarIndex();
            break;
        }
    }//GEN-LAST:event_cercaNomKeyReleased

    //------------------------------------------------------
    
    
    private void entradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entradaKeyPressed
        // TODO add your handling code here:
        ItemTicket t;
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ENTER://Afegeix item al ticket per codi de barres
                String c = entrada.getText();
                Producte p = Funcions.cercaPerCodiBarres(c);
                if(p != null){
                    t = new ItemTicket();
                    t.nom = p.nom;
                    t.preu = p.preu;
                    t.quantitat = 1;
                    Dades.ticketActual.afegirProducte(t);
                }else{
                    Funcions.afegirProducte(c);
                }
                entrada.setText("");
                refrescaLlistes();
                nomProductes.setSelectedIndex(nomProductes.getModel().getSize() - 1);
                
            break;
                
            case KeyEvent.VK_F2: //Imprimir ticket
                String efectiu = (String)JOptionPane.showInputDialog("Efectiu:");
                if(!efectiu.isEmpty()){
                if(efectiu.contains(",")){
                    efectiu = efectiu.replace(",", ".");
                }
                
                Dades.ticketActual.llistaItems = Funcions.colapsaTicket(Dades.ticketActual.llistaItems);
                Dades.ticketActual.calcularTotals();
                String totalTicket = total.getText();
                totalTicket = totalTicket.replace(",", ".");
                
                Dades.ticketActual.Efectiu = Float.parseFloat(efectiu);
                Dades.ticketActual.Canvi = Dades.ticketActual.Efectiu - Float.parseFloat(totalTicket);
                Dades.ticketActual.llistaItems = Funcions.colapsaTicket(Dades.ticketActual.llistaItems);
                
                {
                    try {
                        Funcions.guardarTicket(Dades.ticketActual);
                    } catch (IOException ex) {
                        Logger.getLogger(Interfase.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                Funcions.afegirVendes(Dades.ticketActual);
                Funcions.afegirPrestatges(Dades.ticketActual);
                
                Dades.ticketImprimir = Dades.ticketActual;
                ImprimirTicket pt = new ImprimirTicket();
                pt.imprimir(Dades.format, Dades.configImpresora, Dades.dialegImprimir);
                
                Dades.ticketActual.buidaTicket();
                buidaLlistes();
                }else{
                    JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame,
                    "No s'ha introduit la quantitat en efectiu",
                    "Efectiu",
                    JOptionPane.WARNING_MESSAGE);
                }
            break;
            
            case 106: //Definir quantitat
                if(!"".equals(entrada.getText())){
                    int r = nomProductes.getSelectedIndex();
                    Dades.ticketActual.llistaItems.get(r).quantitat = Float.parseFloat(entrada.getText());
                    refrescaLlistes();
                    nomProductes.setSelectedIndex(r);
                }
                
            break;
            
            case 107: //sumar
                int w = nomProductes.getSelectedIndex();
                Dades.ticketActual.llistaItems.get(w).quantitat = Dades.ticketActual.llistaItems.get(w).quantitat + 1;
                refrescaLlistes();
                nomProductes.setSelectedIndex(w);
            break;
            
            case 109: //restar
                int e = nomProductes.getSelectedIndex();
                Dades.ticketActual.llistaItems.get(e).quantitat = Dades.ticketActual.llistaItems.get(e).quantitat - 1;
                refrescaLlistes();
                nomProductes.setSelectedIndex(e);
            break;
            
            case KeyEvent.VK_DOWN:
                int q = nomProductes.getSelectedIndex()+1;
                if(q<nomProductes.getModel().getSize()){
                    nomProductes.setSelectedIndex(q);
                }
            break;
                
            case KeyEvent.VK_UP:
                int f = nomProductes.getSelectedIndex()-1;
                if(f>=0){
                    nomProductes.setSelectedIndex(f);
                }
            break;
                
            case KeyEvent.VK_DELETE:
                Object[] options = {"Si", "No"};
                int n = JOptionPane.showConfirmDialog(rootPane, options, "Eliminar element?", YES_NO_OPTION, WARNING_MESSAGE);
                if(n == 0){
                    Dades.ticketActual.llistaItems.remove(nomProductes.getSelectedIndex());
                }
            break;
        }
    }//GEN-LAST:event_entradaKeyPressed

    private void llistaNomsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llistaNomsMouseExited
        //cerca.setText(""); //No se si es la millor manera
        //carregarNoms();
    }//GEN-LAST:event_llistaNomsMouseExited
        
    private void llistaGranelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llistaGranelMouseClicked
        ListModel l = llistaGranel.getModel();
        int i = llistaGranel.getSelectedIndex();
        Object e = l.getElementAt(i);
        String nom = e.toString();
        Map.Entry<String, Float> a = Funcions.cercaPerNomGranel(nom);
        ItemTicket t = new ItemTicket();
        t.nom = a.getKey();
        t.preu = a.getValue();
        t.quantitat = (entrada.getText().isEmpty()) ? 1 : Float.parseFloat(entrada.getText());
        Dades.ticketActual.llistaItems.add(t);
        refrescaLlistes();
        nomProductes.setSelectedIndex(nomProductes.getModel().getSize() - 1);
    }//GEN-LAST:event_llistaGranelMouseClicked

    private void llistaGranelnone(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llistaGranelnone
        // TODO add your handling code here:
    }//GEN-LAST:event_llistaGranelnone

    private void llistaGranelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llistaGranelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_llistaGranelMouseExited

    private void nomProductesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_nomProductesValueChanged
        preus.setSelectedIndex(nomProductes.getSelectedIndex());
        quantitats.setSelectedIndex(nomProductes.getSelectedIndex());
        totals.setSelectedIndex(nomProductes.getSelectedIndex());
    }//GEN-LAST:event_nomProductesValueChanged

    private void quantitatsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_quantitatsValueChanged
        preus.setSelectedIndex(quantitats.getSelectedIndex());
        totals.setSelectedIndex(quantitats.getSelectedIndex());
        nomProductes.setSelectedIndex(quantitats.getSelectedIndex());
    }//GEN-LAST:event_quantitatsValueChanged

    private void preusValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_preusValueChanged
        quantitats.setSelectedIndex(preus.getSelectedIndex());
        totals.setSelectedIndex(preus.getSelectedIndex());
        nomProductes.setSelectedIndex(preus.getSelectedIndex());
    }//GEN-LAST:event_preusValueChanged

    private void totalsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_totalsValueChanged
        quantitats.setSelectedIndex(totals.getSelectedIndex());
        nomProductes.setSelectedIndex(totals.getSelectedIndex());
        preus.setSelectedIndex(totals.getSelectedIndex());
    }//GEN-LAST:event_totalsValueChanged

    private void entradaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entradaKeyReleased
        
        ItemTicket t;
        switch(evt.getKeyCode()){
            case 106:
                entrada.setText("");
            break;
                
            case 107:
                entrada.setText("");
            break;
            
            case 109: //sumar, restar o multiplicar
                entrada.setText("");
            break;
                   
            case KeyEvent.VK_S:
                t = new ItemTicket();
                t.nom = "Supermercats varis";
                t.preu = Float.parseFloat(entrada.getText().substring(0, entrada.getText().length()-1));
                t.quantitat = 1;
                Dades.ticketActual.afegirProducte(t);
                refrescaLlistes();
                mostrarIndex();
                entrada.setText("");
                mostrarIndex();
            break;
                
            case KeyEvent.VK_F:
                t = new ItemTicket();
                t.nom = "Fruita i verdura";
                t.preu = Float.parseFloat(entrada.getText().substring(0, entrada.getText().length()-1));
                t.quantitat = 1;
                Dades.ticketActual.afegirProducte(t);
                refrescaLlistes();
                mostrarIndex();
                entrada.setText("");
                mostrarIndex();
            break;
        }
    }//GEN-LAST:event_entradaKeyReleased

    private void entradaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_entradaFocusGained
        // TODO add your handling code here:
        entrada.setBackground(Color.getHSBColor(49, 0, 80));
        cercaNom.setBackground(Color.white);
    }//GEN-LAST:event_entradaFocusGained

    private void cercaNomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cercaNomFocusGained
        // TODO add your handling code here:
        cercaNom.setBackground(Color.getHSBColor(49, 0, 80));
        entrada.setBackground(Color.white);
    }//GEN-LAST:event_cercaNomFocusGained

    private void veureVendesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veureVendesActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("Productes venuts");
        frame.setLocationRelativeTo(null);
        Llistats prestatges = new Llistats();
        prestatges.carregarVendes();
        frame.setSize(810, 700);
        frame.add(prestatges);
        frame.setLocationRelativeTo(this);
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frame.setVisible(true);
    }//GEN-LAST:event_veureVendesActionPerformed

    private void aparcarTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aparcarTicketActionPerformed
        Ticket t = new Ticket();
        for(ItemTicket i: Dades.ticketActual.llistaItems){
            t.afegirProducte(i);
        }
        Dades.ticketsPendents.add(t);
        Dades.ticketActual.buidaTicket();
        refrescaLlistes();
    }//GEN-LAST:event_aparcarTicketActionPerformed

    private void recuperarTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recuperarTicketActionPerformed
        
        if (Dades.ticketsPendents.size() > 0) {
            JFrame frame = new JFrame("Tickets pendents");
            frame.setLocationRelativeTo(null);

            Object[] possibilities = new Object[Dades.ticketsPendents.size()];
            for(ItemTicket i: Dades.ticketsPendents.get(0).llistaItems){
                System.out.print(i.nom);
            }
            for (int i = 0; i < Dades.ticketsPendents.size(); i++) {
                possibilities[i] = i + 1;
            }

            int s = (int) JOptionPane.showInputDialog(frame,
                    "Selecciona el ticket:\n",
                    "Customized Dialog",
                    JOptionPane.PLAIN_MESSAGE,
                    null,
                    possibilities,
                    possibilities[0]);

            Dades.ticketActual = Dades.ticketsPendents.get(0);
            Dades.ticketsPendents.remove(s);
            refrescaLlistes();
            
        } else {
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame,
                    "No hi ha cap ticket aparcat",
                    "Ticket",
                    JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_recuperarTicketActionPerformed

    //------------------------------------------------------
    
    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Interfase().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aparcarTicket;
    private javax.swing.JMenuItem carregaDades;
    private javax.swing.JMenuItem carregarExcel;
    private javax.swing.JTextField cercaNom;
    private static javax.swing.JTextField entrada;
    private javax.swing.JMenu gestioDades;
    private javax.swing.JMenuItem guardarDades;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JList llistaGranel;
    private javax.swing.JList llistaNoms;
    private javax.swing.JMenu mostraLlistes;
    private javax.swing.JList nomProductes;
    private javax.swing.JList preus;
    private javax.swing.JList quantitats;
    private javax.swing.JMenuItem recuperarTicket;
    private javax.swing.JTextField total;
    private javax.swing.JList totals;
    private javax.swing.JMenuItem veureClients;
    private javax.swing.JMenuItem veurePrestatges;
    private javax.swing.JMenuItem veureTicketsPendents;
    private javax.swing.JMenuItem veureVendes;
    // End of variables declaration//GEN-END:variables
}
